#ifndef FCPUT_GRAPHICS_PLOT_H
#define FCPUT_GRAPHICS_PLOT_H

#include "graphics/common.hpp"

FCP_NAMESPACE_BEGIN
FCP_GRAPHICS_NAMESPACE_BEGIN

FCP_GRAPHICS_NAMESPACE_END
FCP_NAMESPACE_END

#endif	// FCPUT_GRAPHICS_PLOT_H
